name: "Coverity Analsysis by using cov-build as capture command."
description: "Will analyze the source code with Coverity Connect."
author: Jouni Lehto
branding:
  icon: code
  color: blue
inputs:
  project:
    description: Coverity Connect project name. If not given, then using github.repository as a default
    required: false
    default: ${{github.repository}}
  stream:
    description: Coverity Connect project stream name. If not given, then using github.ref_name as a default
    required: false
    default: ${{github.ref_name}}
  cov_username:
    description: Coverity Connect username
    required: true
  cov_password:
    description: Coverity Connect password
    required: true
  cov_url:
    description: URL for Coverity Connect where the analysis tar file can be downloaded
    required: true
  cov_installation_dir:
    description: Place where coverity commands are found. Ex. /coverity/bin/. Not required if Coverity tools are in PATH.
    required: false
  intermediate_dir:
    description: Itermediate directory
    required: true
  log_level:
    description: Logging level
    default: DEBUG
    required: false
  teams_webhook_url:
    description: Microsoft Teams WebHook URL. By giving this, the Teams notification is activated
    required: false
  force_commit:
    description: Setting this true, it will do the commit and will not do any checkings.
    default: "false"
    required: false
  dryrun:
    description: Set this true, if you want to run tests and not to do the commit.
    default: "false"
    required: false
  break_build:
    description: Set this true, if you want to break the build, if there are new findings.
    default: "false"
    required: false
  emit_threshold:
    description: With this you can set the emit threshold, the default is 95
    default: '95'
    required: false
  viewID:
    description: ID of that view which result is used to get findings
    required: false
  build_command:
    description: Application build command. Ex. mvn clean install
    required: true
  cov_build_params:
    description: Additional parameters for cov-build phase
    required: false
    default: --fs-capture-search ${{github.workspace}} --fs-capture-search-exclude-regex \"[/\\\\]test[/\\\\]\"
  cov_analysis_params:
    description: Additional parameters for cov-analyze phase
    required: false
    default: --webapp-security --security --strip-path=${{github.workspace}} -en HARDCODED_CREDENTIALS

runs:
  using: composite
  steps:
    # First step is to run the Coverity capture phase with cov-build
    - run: cov-build --dir ${{inputs.intermediate_dir}} ${{inputs.cov_build_params}} ${{inputs.build_command}}
    # Second phase is to run the Coverity Analysis
    - run: cov-analyze --dir ${{inputs.intermediate_dir}} ${{inputs.cov_analysis_params}}
    # Third phase is the commit and that is done with coverity-commit-checker -action.
    - name: Coverity Commit phase
      uses: lejouni/coverity-commit-checker@v5
      with:
        project: ${{inputs.project}}
        stream: ${{inputs.stream}}
        cov_username: ${{inputs.cov_username}}
        cov_password: ${{inputs.cov_password}}
        cov_url: ${{inputs.cov_url}}
        intermediate_dir: ${{inputs.intermediate_dir}}
        cov_installation_dir: ${{inputs.cov_installation_dir}}
        log_level: ${{inputs.log_level}}
        teams_webhook_url: ${{inputs.teams_webhook_url}}
        force_commit: ${{inputs.force_commit}}
        dryrun: ${{inputs.dryrun}}
        break_build: ${{inputs.break_build}}
        emit_threshold: ${{inputs.emit_threshold}}
        viewID: ${{inputs.viewID}}

