name: "Coverity Analsysis by using cov-build as capture command."
description: "Will analyze the source code with Coverity Connect."
author: Jouni Lehto
branding:
  icon: code
  color: blue
inputs:
  log_level:
    description: Logging level
    default: DEBUG
    required: false
  teams_webhook_url:
    description: Microsoft Teams WebHook URL. By giving this, the Teams notification is activated
    required: false
  force_commit:
    description: Setting this true, it will do the commit and will not do any checkings.
    default: "false"
    required: false
  dryrun:
    description: Set this true, if you want to run tests and not to do the commit.
    default: "false"
    required: false
  break_build:
    description: Set this true, if you want to break the build, if there are new findings.
    default: "false"
    required: false
  emit_threshold:
    description: With this you can set the emit threshold, the default is 95
    default: '95'
    required: false
  viewID:
    description: ID of that view which result is used to get findings
    required: false
  build_command:
    description: Application build command. Ex. mvn clean install
    required: true
  cov_build_params:
    description: Additional parameters for cov-build phase
    required: false
    default: --fs-capture-search ${{github.workspace}} --fs-capture-search-exclude-regex \"[/\\\\]test[/\\\\]\"
  cov_analysis_params:
    description: Additional parameters for cov-analyze phase
    required: false
    default: --webapp-security --security --strip-path=${{github.workspace}} -en HARDCODED_CREDENTIALS

runs:
  using: composite
  steps:
    # First step is to run the Coverity capture phase with cov-build
    - run: cov-build --dir ${{env.cov_intermediate_dir}} ${{inputs.cov_build_params}} ${{inputs.build_command}}
      shell: bash
    # Second phase is to run the Coverity Analysis
    - run: cov-analyze --dir ${{env.cov_intermediate_dir}} ${{inputs.cov_analysis_params}}
      shell: bash
    # Fourth phase is the commit and that is done with coverity-commit-checker -action.
    - name: Coverity Commit phase
      uses: lejouni/coverity-commit-checker@v5.6.1
      with:
        project: ${{env.project}}
        stream: ${{env.stream}}
        cov_username: ${{env.cov_username}}
        cov_password: ${{env.cov_password}}
        cov_url: ${{env.cov_url}}
        intermediate_dir: ${{env.cov_intermediate_dir}}
        log_level: ${{inputs.log_level}}
        teams_webhook_url: ${{inputs.teams_webhook_url}}
        force_commit: ${{inputs.force_commit}}
        dryrun: ${{inputs.dryrun}}
        break_build: ${{inputs.break_build}}
        emit_threshold: ${{inputs.emit_threshold}}
        viewID: ${{inputs.viewID}}
